NO MORE EXCUSES, THE SPACE LAW LINK IS RIGHT FUCKING THERE
OracleStation/OracleStation pull request #774
Opened 2018-03-29 20:47 UTC by Ziiro

:cl: 
add: Security officers have space law shoved in their face on joining
tweak: Captain now requires command experience
/:cl:

READ GODDAMNIT, READ.
![nvidia share_2018-03-29_14-47-01](https://user-images.githubusercontent.com/26494679/38112730-15431060-3360-11e8-9810-dbedb278d93e.png)

Also maybe we'll get less shitter Captains with the fact it requires command experience, rather than just.. crew experience.

2018-03-30 09:28 UTC, FlattestGuitar requested changes
Also, we don't use the account age system, only EXP. No point in changing those.

2018-03-30 09:28 UTC, FlattestGuitar commented on code/modules/jobs/job_types/security.dm
> +	special_notice = "Space law is THE LAW. Not a suggestion."
It's `Space Law`. Capitalize the L

2018-03-30 19:49 UTC, swagbringer commented
Please merge, these captains are killing me

2018-03-30 19:55 UTC, AndrewMontagne approved these changes
LGTM

2018-03-31 10:17 UTC, FlattestGuitar approved these changes

2018-03-31 10:17 UTC, merged